# This file was generated by GoReleaser. DO NOT EDIT.
cask "drift" do
  version "0.1.0-alpha.2"

  on_macos do
    on_intel do
      sha256 "2f534fabc47f8722b765f1ffe0347c333e64db6d66a0a026334d606f1d38cbda"
      url "https://github.com/sufforest/drift/releases/download/v#{version}/drift_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "73c283f2ff970f5973c31fa22f25b4230ebea6699114d7afcb2d55ea0d9ccfa2"
      url "https://github.com/sufforest/drift/releases/download/v#{version}/drift_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b32bcd80ce509af6de795a771dead75b35d9c3fa9bff5b263c5d0a141b0ca4d1"
      url "https://github.com/sufforest/drift/releases/download/v#{version}/drift_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "dae3cc3a04c2e12695b2532046d85e1302a3794583c8ff8459836cef865ae886"
      url "https://github.com/sufforest/drift/releases/download/v#{version}/drift_#{version}_linux_arm64.tar.gz"
    end
  end

  name "drift"
  desc "End-to-end encrypted workspaces on S3-compatible buckets (R2, S3, B2, MinIO)"
  homepage "https://github.com/sufforest/drift"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "rclone",
    ]

  binary "drift"

  # No zap stanza required

end
