# This file was generated by GoReleaser. DO NOT EDIT.
cask "drift" do
  version "0.1.0-alpha.3"

  on_macos do
    on_intel do
      sha256 "b2aba8795264ac3fdfeb5f92d01fdbbe00aa70f7e18e162b623b3cc54b8d3e6c"
      url "https://github.com/sufforest/drift/releases/download/v#{version}/drift_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8db9a26bf4236310001ed1b51bc3a48b5b654755f9a8c6835afa5b84b9af06b5"
      url "https://github.com/sufforest/drift/releases/download/v#{version}/drift_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f04ea5a0b971ffeaecf41fa7cd6e6a996d0b037d89debd219d4528a79b0f46a6"
      url "https://github.com/sufforest/drift/releases/download/v#{version}/drift_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3bbcfbc02151e7ff8f26e69c5f7462292d50db41818c9428b2d41d8d4c37a1a7"
      url "https://github.com/sufforest/drift/releases/download/v#{version}/drift_#{version}_linux_arm64.tar.gz"
    end
  end

  name "drift"
  desc "End-to-end encrypted workspaces on S3-compatible buckets (R2, S3, B2, MinIO)"
  homepage "https://github.com/sufforest/drift"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "rclone",
    ]

  binary "drift"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/drift"]
    end
  end

  # No zap stanza required

end
